name: Build python wheel package
on: [ push, create ]
jobs:
  make-wheel:
    name: Build wheel package
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip3 install wheel setuptools setuptools_scm
      - name: Build wheel
        run: make wheel
      - name: Upload artifact wheel (at a push)
        uses: actions/upload-artifact@v2
        with:
          name: wheel package
          path: dist
      - name: Upload to pypi (at a tag)
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
  documentation:
    name: Build document pages
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Build document
        run: make html docx pdf
      - name: Upload artifact files (at a push)
        uses: actions/upload-artifact@v2
        with:
          name: documents
          path: docs/Out

