name: Build python wheel package
on: [ push, create ]
jobs:
  make-wheel:
    name: Build wheel package
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip3 install wheel setuptools setuptools_scm
      - name: Build wheel
        run: make wheel
      - name: Upload artifact wheel (at a push)
        uses: actions/upload-artifact@v2
        with:
          name: wheel package
          path: dist
      - name: Upload to pypi (at a tag)
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
  documentation:
    name: Build document pages
    runs-on: ubuntu-latest
    container:
      image: k4zuki/pandocker-alpine:3.2-core
    if: "contains(github.event.head_commit.message, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Setup safe directory for git
        run: |
          repo=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
          git config --global --add safe.directory /__w/${repo}/${repo}
      - name: Update dependencies
        run: |
          pip3 install pandocker-lua-filters docx-coreprop-writer
          pip3 install git+https://github.com/k4zuki/pandoc_misc.git@2.16.2
      - name: Build document
        run: make docx
      - name: Upload artifact files (at a push)
        uses: actions/upload-artifact@v2
        with:
          name: documents
          path: docs/Out

